[package]
name = "gbc-plus"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { version = "2.3.1", features = ["serde"] }
chrono = "0.4.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ringbuf="0.4.8"
bincode = { version = "2.0.1", features = ["serde"]}