[package]
name = "gbc-plus-mobile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies.gbc-plus]
path = "../"

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
swift-bridge = "0.1"
ringbuf="0.4.8"